name: Ubuntu Build and Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          lfs: true
          clean: true

      - name: Install Dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install gcc g++ cmake protobuf-compiler -y

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake -DUNIT_TESTING=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug ..

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      - name: Test
        run: |
          cd build
          ctest --verbose
